exports.up = async (sql) => {

await sql `
CREATE TABLE users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  passwort_hash varchar(80) NOT NULL,
  user_name varchar(20) NOT NULL,
  isAccepted boolean)`};

exports.down = async sql => {
await sql `
DROP TABLE users`

};
